language: elixir
sudo: false
elixir:
  - 1.4
  - 1.5.0-rc.0
otp_release:
  - 19.3
  - 20.0
matrix:
  allow_failures:
    - elixir: 1.5.0-rc.0
script: mix test.ci
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - steve@stevedomin.com
