language: elixir
sudo: false
cache:
  directories:
    - _build
    - deps
branches:
  only:
    - master
elixir:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
otp_release:
  - 19.3
  - 20.3
  - 21.0
matrix:
  exclude:
  - elixir: 1.4
    otp_release: 21.0
  - elixir: 1.5
    otp_release: 21.0
  - elixir: 1.6
    otp_release: 19.3
  - elixir: 1.7
    otp_release: 19.3
  - elixir: 1.7
    otp_release: 20.3
script: mix test.ci
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - steve@stevedomin.com
