name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ['1.13', '1.12', '1.11', '1.10']
        otp: ['24.x', '23.x', '22.x']
        exclude:
          - elixir: '1.10'
            otp: '24.x'
          - elixir: '1.13'
            otp: '22.x'
        include:
          - lint: lint
            elixir: '1.13'
            otp: '24.x'
          - elixir: '1.13'
            otp: '25.x'

    steps:
      - uses: actions/checkout@v2

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore dependencies cache
        uses: actions/cache@v2
        id: cache-elixir-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-${{ matrix.otp }}

      - name: Install Dependencies
        if: steps.cache-elixir-deps.outputs.cache-hit != 'true'
        run: MIX_ENV=test mix do deps.get, deps.compile, compile

      - run: mix format --check-formatted
        if: matrix.lint

      - name: Run Tests
        run: mix test
