name: Elixir CI

on: [issues, pull_request]

env:
  current_maintainer: Po Chen `@princemaple`

jobs:
  hello:
    name: Say hello
    runs-on: ubuntu-latest

    steps:
      - name: First interaction
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hi 👋,
            
            Thanks for reaching out.
            If we don't get back to you soon enough, feel free to give us another ping!
            The current maintainer is ${{ env.current_maintainer }}
          pr-message: |
            Hi 👋,
            
            Thanks for the PR!
            If we don't get back to you soon enough, feel free to give us another ping!
            The current maintainer is ${{ env.current_maintainer }}
